// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
std::unordered_map<std::string, std::string> rcpp_hello_world();
RcppExport SEXP _ppm_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_ppm_simple();
RcppExport SEXP _rcpp_module_boot_ppm_decay();
RcppExport SEXP _rcpp_module_boot_record_decay();
RcppExport SEXP _rcpp_module_boot_unif_module();

static const R_CallMethodDef CallEntries[] = {
    {"_ppm_rcpp_hello_world", (DL_FUNC) &_ppm_rcpp_hello_world, 0},
    {"_rcpp_module_boot_ppm_simple", (DL_FUNC) &_rcpp_module_boot_ppm_simple, 0},
    {"_rcpp_module_boot_ppm_decay", (DL_FUNC) &_rcpp_module_boot_ppm_decay, 0},
    {"_rcpp_module_boot_record_decay", (DL_FUNC) &_rcpp_module_boot_record_decay, 0},
    {"_rcpp_module_boot_unif_module", (DL_FUNC) &_rcpp_module_boot_unif_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ppm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
